#!/usr/bin/env node
/**
 * Generates webapp/src/library/library.generated.ts from the real course
 * repo: 35 modules (track1-core-engine, track2-applied-layer) plus 8
 * prerequisites. Real source files and DECISIONS.md are read directly,
 * never hand-transcribed. Doc links come from docs-by-group.mjs (shared
 * per phase, all verified live during authoring).
 *
 * Run with: node scripts/generate-library.mjs
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { MODULES, PREREQUISITES } from './module-index.mjs';
import { DOCS_BY_GROUP } from './docs-by-group.mjs';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const webappRoot = join(__dirname, '..');
const courseRoot = join(webappRoot, '..');

const CODE_EXT = new Set(['.py', '.c', '.h']);

function collectFiles(dirAbs) {
  const out = [];
  for (const entry of readdirSync(dirAbs, { withFileTypes: true })) {
    if (!entry.isFile()) continue;
    const ext = extname(entry.name);
    if (!CODE_EXT.has(ext)) continue;
    out.push({ name: entry.name, lang: ext === '.py' ? 'python' : 'c', code: readFileSync(join(dirAbs, entry.name), 'utf8') });
  }
  out.sort((a, b) => a.name.localeCompare(b.name));
  return out;
}

function parseDecisions(dirAbs) {
  const path = join(dirAbs, 'DECISIONS.md');
  if (!existsSync(path)) return [];
  const text = readFileSync(path, 'utf8');
  const lines = text.split('\n');
  const blocks = [];
  let current = null;
  for (const line of lines) {
    const m = line.match(/^## (.+)$/);
    if (m) {
      if (current) blocks.push(current);
      current = { title: m[1].trim(), bodyLines: [] };
    } else if (current) {
      current.bodyLines.push(line);
    }
  }
  if (current) blocks.push(current);
  // Drop the trailing "Decisions We Made" summary table and "What We
  // Proved" sections — they restate the per-decision cards above; keeping
  // just the individual decisions avoids showing everything twice.
  return blocks
    .filter((b) => !/^Decisions We Made$/i.test(b.title) && !/^What We Proved$/i.test(b.title))
    .map((b) => ({ title: b.title, body: b.bodyLines.join('\n').trim() }));
}

function stripTags(html) {
  return html
    .replace(/<[^>]+>/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\s+/g, ' ')
    .trim();
}

function extractPrereqSummary(htmlAbs) {
  const html = readFileSync(htmlAbs, 'utf8');
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*)<\/body>/);
  const body = bodyMatch ? bodyMatch[1] : html;
  const firstH2Idx = body.search(/<h2/);
  const introHtml = firstH2Idx === -1 ? body : body.slice(0, firstH2Idx);
  const paras = [...introHtml.matchAll(/<p[^>]*>([\s\S]*?)<\/p>/g)].map((m) => stripTags(m[1]));
  const headings = [...body.matchAll(/<h2[^>]*>([\s\S]*?)<\/h2>/g)].map((m) => stripTags(m[1]));
  return { summary: paras.join(' '), headings };
}

// Every tutorial.html / prerequisite page is a fragment (no <html>/<head>/
// <body>) that links a shared stylesheet and carries one inline <style>
// overriding --accent for that page. Strip the <link> (dead inside a
// srcdoc iframe with no filesystem) — the design system gets inlined once,
// shared, at render time instead of duplicated per module.
function readTutorialFragment(htmlAbs) {
  if (!existsSync(htmlAbs)) return '';
  return readFileSync(htmlAbs, 'utf8').replace(/<link[^>]*design-system\.css[^>]*>\s*/i, '');
}

function tsString(s) {
  return JSON.stringify(s);
}

const designSystemCss = readFileSync(join(courseRoot, 'assets', 'design-system.css'), 'utf8');

let out = '';
out += '// AUTO-GENERATED by scripts/generate-library.mjs — do not hand-edit.\n';
out += '// Source of truth: the real course directories (track1-core-engine, track2-applied-layer, prerequisites).\n\n';
out += 'export interface LibFile { name: string; lang: string; code: string }\n';
out += 'export interface LibDecision { title: string; body: string }\n';
out += 'export interface LibDoc { title: string; description: string; url: string }\n';
out += 'export interface LibModule { num: number; id: string; title: string; proves: string; dir: string; depends: number[]; track: number; phase: string; hasLive: boolean; files: LibFile[]; decisions: LibDecision[]; docs: LibDoc[]; tutorial: string }\n';
out += 'export interface LibPrereq { id: string; title: string; summary: string; headings: string[]; docs: LibDoc[]; tutorial: string }\n\n';
out += `export const DESIGN_SYSTEM_CSS = ${tsString(designSystemCss)};\n\n`;

out += 'export const LIBRARY_MODULES: LibModule[] = [\n';
for (const m of MODULES) {
  const dirAbs = join(courseRoot, m.dir);
  const files = collectFiles(dirAbs);
  const decisions = parseDecisions(dirAbs);
  const docs = DOCS_BY_GROUP[m.group] ?? [];
  const tutorial = readTutorialFragment(join(dirAbs, 'tutorial.html'));

  out += `  {\n`;
  out += `    num: ${m.num}, id: ${tsString(m.id)}, title: ${tsString(m.title)}, proves: ${tsString(m.proves)},\n`;
  out += `    dir: ${tsString(m.dir)}, depends: ${JSON.stringify(m.depends)}, track: ${m.track}, phase: ${tsString(m.phase)},\n`;
  out += `    hasLive: ${m.hasLive ? 'true' : 'false'}, tutorial: ${tsString(tutorial)},\n`;
  out += `    files: [\n`;
  for (const f of files) out += `      { name: ${tsString(f.name)}, lang: ${tsString(f.lang)}, code: ${tsString(f.code)} },\n`;
  out += `    ],\n`;
  out += `    decisions: [\n`;
  for (const d of decisions) out += `      { title: ${tsString(d.title)}, body: ${tsString(d.body)} },\n`;
  out += `    ],\n`;
  out += `    docs: [\n`;
  for (const d of docs) out += `      { title: ${tsString(d.title)}, description: ${tsString(d.description)}, url: ${tsString(d.url)} },\n`;
  out += `    ],\n`;
  out += `  },\n`;
}
out += '];\n\n';

out += 'export const LIBRARY_PREREQUISITES: LibPrereq[] = [\n';
for (const p of PREREQUISITES) {
  const htmlAbs = join(courseRoot, p.dir, p.file);
  const { summary, headings } = extractPrereqSummary(htmlAbs);
  const docs = DOCS_BY_GROUP[p.group] ?? [];
  const tutorial = readTutorialFragment(htmlAbs);
  out += `  { id: ${tsString(p.id)}, title: ${tsString(p.title)}, summary: ${tsString(summary)}, headings: ${JSON.stringify(headings)}, tutorial: ${tsString(tutorial)}, docs: [\n`;
  for (const d of docs) out += `    { title: ${tsString(d.title)}, description: ${tsString(d.description)}, url: ${tsString(d.url)} },\n`;
  out += `  ] },\n`;
}
out += '];\n';

writeFileSync(join(webappRoot, 'src', 'library', 'library.generated.ts'), out, 'utf8');

const totalFiles = MODULES.reduce((n, m) => n + collectFiles(join(courseRoot, m.dir)).length, 0);
const totalDecisions = MODULES.reduce((n, m) => n + parseDecisions(join(courseRoot, m.dir)).length, 0);
console.log(`Wrote src/library/library.generated.ts: ${MODULES.length} modules (${totalFiles} files, ${totalDecisions} decisions), ${PREREQUISITES.length} prerequisites.`);
