/**
 * The full 35-module, 2-track course map, transcribed from the real
 * ROADMAP.md tables (module number, id, "what it proves", directory,
 * depends-on), plus the 8 standalone prerequisites. Each entry is tagged
 * with a `group` used to look up shared, verified doc links in
 * docs-by-group.mjs — curating 43 unique doc sets wasn't tractable, but
 * every phase's shared set is real and fetched-and-confirmed, not guessed.
 */

export const PREREQUISITES = [
  { id: '01_virtual_memory', title: 'Virtual Memory', dir: 'prerequisites', file: '01_virtual_memory.html', group: 'bare-metal' },
  { id: '02_privilege_rings', title: 'Privilege Rings', dir: 'prerequisites', file: '02_privilege_rings.html', group: 'bare-metal' },
  { id: '03_syscalls', title: 'Syscalls', dir: 'prerequisites', file: '03_syscalls.html', group: 'bare-metal' },
  { id: '04_processes_and_threads', title: 'Processes and Threads', dir: 'prerequisites', file: '04_processes_and_threads.html', group: 'process-ipc' },
  { id: '05_handles_and_fds', title: 'Handles and File Descriptors', dir: 'prerequisites', file: '05_handles_and_fds.html', group: 'process-ipc' },
  { id: '06_bytes_hex_endianness', title: 'Bytes, Hex, and Endianness', dir: 'prerequisites', file: '06_bytes_hex_endianness.html', group: 'networking' },
  { id: '07_ipc_channels', title: 'IPC Channels', dir: 'prerequisites', file: '07_ipc_channels.html', group: 'process-ipc' },
  { id: '08_origins_and_urls', title: 'Origins and URLs', dir: 'prerequisites', file: '08_origins_and_urls.html', group: 'networking' },
];

export const MODULES = [
  // ---- Track 1: Core Engine ----
  { num: 1, id: 'mem_addressing', title: 'Virtual Memory Addressing', proves: "Proves a process's virtual address space is a translated illusion, not physical memory — the same virtual address in two processes maps to different physical RAM", dir: 'track1-core-engine/phase1_bare_metal/01_mem_addressing', depends: [], group: 'bare-metal', hasLive: true, track: 1, phase: 'Phase 1: Bare Metal Foundation' },
  { num: 2, id: 'privilege_rings', title: 'Privilege Rings', proves: 'Proves user-mode code physically cannot execute a privileged instruction without trapping into the kernel', dir: 'track1-core-engine/phase1_bare_metal/02_privilege_rings', depends: [], group: 'bare-metal', hasLive: true, track: 1, phase: 'Phase 1: Bare Metal Foundation' },
  { num: 3, id: 'syscall_boundary', title: 'The Syscall Boundary', proves: 'Proves every "browser action" (open a file, open a socket) is a request that crosses into kernel code, traceable and interceptable', dir: 'track1-core-engine/phase1_bare_metal/03_syscall_boundary', depends: [], group: 'bare-metal', track: 1, phase: 'Phase 1: Bare Metal Foundation' },
  { num: 4, id: 'process_anatomy', title: 'Process Anatomy', proves: 'Proves a process is a kernel-held data structure plus an address space plus threads — not "a running .exe"', dir: 'track1-core-engine/phase1_bare_metal/04_process_anatomy', depends: [], group: 'bare-metal', track: 1, phase: 'Phase 1: Bare Metal Foundation' },
  { num: 5, id: 'process_creation', title: 'Process Creation', proves: "Proves spawning a child process creates a genuinely distinct address space — writing to \"the same\" variable address in parent and child never collide", dir: 'track1-core-engine/phase2_process_ipc/05_process_creation', depends: [4], group: 'process-ipc', track: 1, phase: 'Phase 2: Process & IPC Substrate' },
  { num: 6, id: 'pipes_and_sockets', title: 'Pipes and Sockets', proves: 'Proves two isolated processes can only exchange data through a kernel-mediated channel that must be explicitly set up — nothing crosses by accident', dir: 'track1-core-engine/phase2_process_ipc/06_pipes_and_sockets', depends: [5], group: 'process-ipc', track: 1, phase: 'Phase 2: Process & IPC Substrate' },
  { num: 7, id: 'shared_memory', title: 'Shared Memory', proves: 'Proves the one deliberate exception to process isolation is explicit shared memory, and that it must be opted into by both sides', dir: 'track1-core-engine/phase2_process_ipc/07_shared_memory', depends: [5], group: 'process-ipc', track: 1, phase: 'Phase 2: Process & IPC Substrate' },
  { num: 8, id: 'toy_browser_shell', title: 'Toy Browser Shell', proves: 'Proves a "browser" can be correctly modeled as one Browser Process plus N Renderer Processes exchanging structured IPC messages — this is the seed of the toy browser', dir: 'track1-core-engine/phase2_process_ipc/08_toy_browser_shell', depends: [5, 6, 7], group: 'process-ipc', track: 1, phase: 'Phase 2: Process & IPC Substrate' },
  { num: 9, id: 'least_privilege_tokens', title: 'Least-Privilege Tokens', proves: "Proves a process's OS-level permissions can be stripped after spawn, so a renderer literally cannot open a file its parent can", dir: 'track1-core-engine/phase3_sandboxing/09_least_privilege_tokens', depends: [4], group: 'sandboxing', track: 1, phase: 'Phase 3: Isolation & Sandboxing' },
  { num: 10, id: 'syscall_filtering', title: 'Syscall Filtering', proves: 'Proves a process can be blocked from making certain syscalls at all, even if compromised code inside it tries', dir: 'track1-core-engine/phase3_sandboxing/10_syscall_filtering', depends: [3], group: 'sandboxing', track: 1, phase: 'Phase 3: Isolation & Sandboxing' },
  { num: 11, id: 'site_isolation_model', title: 'Site Isolation Model', proves: 'Proves putting two different origins in two different sandboxed OS processes makes cross-origin memory reads impossible without going through IPC', dir: 'track1-core-engine/phase3_sandboxing/11_site_isolation_model', depends: [8], group: 'sandboxing', track: 1, phase: 'Phase 3: Isolation & Sandboxing' },
  { num: 12, id: 'aslr_and_leaks', title: 'ASLR and Info Leaks', proves: 'Proves ASLR only raises exploit cost by randomizing addresses — it proves nothing once a single info-leak exists', dir: 'track1-core-engine/phase4_mitigations/12_aslr_and_leaks', depends: [1], group: 'mitigations', track: 1, phase: 'Phase 4: Memory Safety & Exploit Mitigations' },
  { num: 13, id: 'dep_nx_w_xor_x', title: 'DEP / NX / W^X', proves: 'Proves W^X blocks code written into data memory from ever executing, by triggering the fault and then showing the sanctioned alternative', dir: 'track1-core-engine/phase4_mitigations/13_dep_nx_w_xor_x', depends: [1], group: 'mitigations', track: 1, phase: 'Phase 4: Memory Safety & Exploit Mitigations' },
  { num: 14, id: 'stack_canaries_cfi', title: 'Stack Canaries & CFI', proves: "Proves canaries/CFI catch control-flow hijacks only at specific checkpoints, not universally — shows a naive smash caught, and why a smarter one wouldn't be", dir: 'track1-core-engine/phase4_mitigations/14_stack_canaries_cfi', depends: [], group: 'mitigations', track: 1, phase: 'Phase 4: Memory Safety & Exploit Mitigations' },

  // ---- Track 2: Applied Layer ----
  { num: 15, id: 'dns_tcp_tls_handshake', title: 'DNS / TCP / TLS Handshake', proves: 'Proves what "loading a URL" costs before a single byte of HTML arrives', dir: 'track2-applied-layer/phase5_networking/15_dns_tcp_tls_handshake', depends: [6, 8], group: 'networking', track: 2, phase: 'Phase 5: Networking' },
  { num: 16, id: 'http_parsing', title: 'HTTP Parsing', proves: 'Proves an HTTP response is structured text over a socket, hand-parseable with no framework magic', dir: 'track2-applied-layer/phase5_networking/16_http_parsing', depends: [6], group: 'networking', hasLive: true, track: 2, phase: 'Phase 5: Networking' },
  { num: 17, id: 'origin_model_sop', title: 'The Origin Model (SOP)', proves: 'Proves the browser, not the server, is what enforces that script from origin A cannot read a response from origin B', dir: 'track2-applied-layer/phase5_networking/17_origin_model_sop', depends: [8, 11], group: 'networking', track: 2, phase: 'Phase 5: Networking' },
  { num: 18, id: 'cors_preflight', title: 'CORS Preflight', proves: 'Proves CORS is an opt-in relaxation of SOP via an extra validated round trip, not an independent security mechanism', dir: 'track2-applied-layer/phase5_networking/18_cors_preflight', depends: [17], group: 'networking', track: 2, phase: 'Phase 5: Networking' },
  { num: 19, id: 'html_tokenizer', title: 'HTML Tokenizer', proves: 'Proves HTML parsing is a state machine with defined recovery behavior, not "reading tags"', dir: 'track2-applied-layer/phase6_parsing_dom/19_html_tokenizer', depends: [8], group: 'parsing-dom', hasLive: true, track: 2, phase: 'Phase 6: Parsing & the DOM' },
  { num: 20, id: 'dom_tree_builder', title: 'DOM Tree Builder', proves: 'Proves the DOM is built incrementally from tokens under insertion-mode rules, not assembled all at once', dir: 'track2-applied-layer/phase6_parsing_dom/20_dom_tree_builder', depends: [19], group: 'parsing-dom', hasLive: true, track: 2, phase: 'Phase 6: Parsing & the DOM' },
  { num: 21, id: 'css_parser_cssom', title: 'CSS Parser & CSSOM', proves: 'Proves CSS becomes a separate object tree (CSSOM), parsed independently of the DOM and merged later', dir: 'track2-applied-layer/phase6_parsing_dom/21_css_parser_cssom', depends: [19], group: 'parsing-dom', track: 2, phase: 'Phase 6: Parsing & the DOM' },
  { num: 22, id: 'style_computation', title: 'Style Computation', proves: 'Proves every DOM node gets one fully resolved computed style via cascade + specificity before any pixel exists', dir: 'track2-applied-layer/phase7_rendering/22_style_computation', depends: [20, 21], group: 'rendering', track: 2, phase: 'Phase 7: Rendering' },
  { num: 23, id: 'layout_box_model', title: 'Layout & the Box Model', proves: 'Proves layout is a recursive geometry pass that produces real x/y/width/height boxes from styled nodes', dir: 'track2-applied-layer/phase7_rendering/23_layout_box_model', depends: [22], group: 'rendering', track: 2, phase: 'Phase 7: Rendering' },
  { num: 24, id: 'paint_and_composite', title: 'Paint & Composite', proves: 'Proves paint (pixels) and composite (layers) are separate stages — and why a compositor-only style change skips layout and paint entirely', dir: 'track2-applied-layer/phase7_rendering/24_paint_and_composite', depends: [23], group: 'rendering', track: 2, phase: 'Phase 7: Rendering' },
  { num: 25, id: 'js_lexer_parser', title: 'JS Lexer & Parser', proves: 'Proves JS source becomes an AST before a single line executes', dir: 'track2-applied-layer/phase8_js_engine/25_js_lexer_parser', depends: [8], group: 'js-engine', track: 2, phase: 'Phase 8: The JS Engine' },
  { num: 26, id: 'tree_walking_interpreter', title: 'Tree-Walking Interpreter', proves: 'Proves the naive way to "run" JS is direct AST evaluation, and measures why that’s slow', dir: 'track2-applied-layer/phase8_js_engine/26_tree_walking_interpreter', depends: [25], group: 'js-engine', track: 2, phase: 'Phase 8: The JS Engine' },
  { num: 27, id: 'bytecode_vm', title: 'Bytecode VM', proves: 'Proves a bytecode VM is a deliberate engineering response to interpreter overhead, measured against Module 26', dir: 'track2-applied-layer/phase8_js_engine/27_bytecode_vm', depends: [26], group: 'js-engine', track: 2, phase: 'Phase 8: The JS Engine' },
  { num: 28, id: 'event_loop_microtasks', title: 'Event Loop & Microtasks', proves: 'Proves JS concurrency is single-threaded cooperative scheduling via task/microtask queues, not real parallelism', dir: 'track2-applied-layer/phase8_js_engine/28_event_loop_microtasks', depends: [27], group: 'js-engine', track: 2, phase: 'Phase 8: The JS Engine' },
  { num: 29, id: 'cookies_samesite', title: 'Cookies & SameSite', proves: 'Proves SameSite is an origin-adjacent boundary enforced by the browser on outgoing requests, set by a server-controlled flag', dir: 'track2-applied-layer/phase9_policy_layer/29_cookies_samesite', depends: [17], group: 'policy', track: 2, phase: 'Phase 9: The Policy Layer' },
  { num: 30, id: 'csp_enforcement', title: 'CSP Enforcement', proves: 'Proves CSP is a browser-side allowlist checked before script/resource execution, not a server-side filter', dir: 'track2-applied-layer/phase9_policy_layer/30_csp_enforcement', depends: [20, 25], group: 'policy', track: 2, phase: 'Phase 9: The Policy Layer' },
  { num: 31, id: 'mixed_content_hsts', title: 'Mixed Content & HSTS', proves: 'Proves HSTS and mixed-content blocking exist specifically to prevent silent HTTPS→HTTP downgrade', dir: 'track2-applied-layer/phase9_policy_layer/31_mixed_content_hsts', depends: [15], group: 'policy', track: 2, phase: 'Phase 9: The Policy Layer' },
  { num: 32, id: 'xss_csrf_on_toy_browser', title: 'XSS/CSRF on the Toy Browser', proves: 'Proves a real XSS/CSRF payload succeeds against your own toy browser until the specific policy module is wired in, then fails after', dir: 'track2-applied-layer/phase10_attack_surface/32_xss_csrf_on_toy_browser', depends: [17, 29, 30], group: 'attack-surface', track: 2, phase: 'Phase 10: The Attack Surface' },
  { num: 33, id: 'clickjacking_uxss', title: 'Clickjacking & UXSS', proves: 'Proves clickjacking exploits the compositor/paint model and UXSS exploits a site-isolation gap — demonstrated against your own stack', dir: 'track2-applied-layer/phase10_attack_surface/33_clickjacking_uxss', depends: [11, 24], group: 'attack-surface', track: 2, phase: 'Phase 10: The Attack Surface' },
  { num: 34, id: 'side_channel_timing', title: 'Side-Channel Timing', proves: 'Proves a non-weaponized timing side-channel can leak cross-origin data even when SOP and site isolation block direct reads — the reason Site Isolation targets process boundaries, not just script checks', dir: 'track2-applied-layer/phase10_attack_surface/34_side_channel_timing', depends: [11, 17], group: 'attack-surface', track: 2, phase: 'Phase 10: The Attack Surface' },
  { num: 35, id: 'sandbox_escape_chain', title: 'Sandbox Escape Chain', proves: 'Proves a full browser compromise requires defeating multiple independently-built layers together (a mitigation bypass and a syscall-filter bypass), tying both tracks into one attacker’s-eye chain', dir: 'track2-applied-layer/phase10_attack_surface/35_sandbox_escape_chain', depends: [10, 13, 14], group: 'attack-surface', track: 2, phase: 'Phase 10: The Attack Surface' },
];
